/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "outline": "#737686",
        "on-secondary-fixed": "#370e00",
        "on-surface": "#1b1b1b",
        "on-tertiary-container": "#c7ffca",
        "secondary-fixed-dim": "#ffb599",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "primary": "#004ac6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#571a00",
        "tertiary": "#006329",
        "surface-bright": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f9",
        "on-primary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fd651e",
        "error": "#ba1a1a",
        "inverse-primary": "#b4c5ff",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#62df7d",
        "inverse-surface": "#303030",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "tertiary-fixed": "#7ffc97",
        "on-secondary-fixed-variant": "#7f2b00",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "secondary": "#a73a00",
        "on-tertiary-fixed": "#002109",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "on-background": "#1b1b1b",
        "outline-variant": "#c3c6d7",
        "secondary-fixed": "#ffdbce",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#005320",
        "surface-dim": "#dadada",
        "tertiary-container": "#007f36",
        "on-primary-container": "#eeefff",
        "background": "#f9f9f9"
      },
      fontFamily: {
        "display": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
};
